# Generated by Django 3.2.9 on 2021-11-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendjang', '0002_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterange',
            name='task_myset',
        ),
    ]
