# Generated by Django 3.2.9 on 2021-11-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendjang', '0004_task_m2m_to_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
    ]
