# Generated by Django 6.1.1 on 2026-09-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendjang', '0005_delete_scheduledtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
