# Generated by Django 6.1.1 on 2026-09-12 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendjang', '0006_alter_tag_description_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
